version: '3'

services:
  localk8s:
    image: localk8s:${TAG:-latest}
    build: .
    container_name: localk8s
    hostname: hip-advertise-service
    working_dir: "/usr/src"
    command: "python tornado/server.py"
    volumes:
      - ".:/usr/src"
    ports:
      - "11001:8888"
